# Generated by Django 3.1.1 on 2020-10-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201005_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(verbose_name='Slug сообщества'),
        ),
    ]
